# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\project_ltmm\encrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encryption(object):
    def setupUi(self, Encryption):
        Encryption.setObjectName("Encryption")
        Encryption.resize(1329, 829)
        self.back_button = QtWidgets.QPushButton(Encryption)
        self.back_button.setGeometry(QtCore.QRect(570, 790, 171, 31))
        self.back_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.back_button.setObjectName("back_button")
        self.browse_button = QtWidgets.QPushButton(Encryption)
        self.browse_button.setGeometry(QtCore.QRect(440, 60, 181, 41))
        self.browse_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.browse_button.setObjectName("browse_button")
        self.aes_button = QtWidgets.QPushButton(Encryption)
        self.aes_button.setGeometry(QtCore.QRect(230, 300, 231, 41))
        self.aes_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.aes_button.setObjectName("aes_button")
        self.des_button = QtWidgets.QPushButton(Encryption)
        self.des_button.setGeometry(QtCore.QRect(550, 300, 231, 41))
        self.des_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.des_button.setObjectName("des_button")
        self.rc4_button = QtWidgets.QPushButton(Encryption)
        self.rc4_button.setGeometry(QtCore.QRect(860, 300, 231, 41))
        self.rc4_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.rc4_button.setObjectName("rc4_button")
        self.choose_label = QtWidgets.QLabel(Encryption)
        self.choose_label.setGeometry(QtCore.QRect(60, 60, 341, 41))
        self.choose_label.setStyleSheet("font: bold;\n"
"font-size: 20pt\n"
"")
        self.choose_label.setObjectName("choose_label")
        self.key_label = QtWidgets.QLabel(Encryption)
        self.key_label.setGeometry(QtCore.QRect(90, 130, 261, 41))
        self.key_label.setStyleSheet("font: bold;\n"
"font-size: 20pt\n"
"")
        self.key_label.setObjectName("key_label")
        self.key_edit = QtWidgets.QTextEdit(Encryption)
        self.key_edit.setGeometry(QtCore.QRect(380, 130, 471, 41))
        self.key_edit.setObjectName("key_edit")
        self.img_label = QtWidgets.QLabel(Encryption)
        self.img_label.setGeometry(QtCore.QRect(230, 420, 161, 31))
        self.img_label.setStyleSheet("font-size: 15pt;\n"
"font: bold\n"
"")
        self.img_label.setObjectName("img_label")
        self.img_label_2 = QtWidgets.QLabel(Encryption)
        self.img_label_2.setGeometry(QtCore.QRect(900, 420, 201, 31))
        self.img_label_2.setStyleSheet("font-size: 15pt;\n"
"font: bold\n"
"")
        self.img_label_2.setObjectName("img_label_2")
        self.img = QtWidgets.QLabel(Encryption)
        self.img.setGeometry(QtCore.QRect(120, 460, 381, 301))
        self.img.setText("")
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.enimg = QtWidgets.QLabel(Encryption)
        self.enimg.setGeometry(QtCore.QRect(820, 460, 371, 311))
        self.enimg.setText("")
        self.enimg.setScaledContents(True)
        self.enimg.setObjectName("enimg")
        self.label = QtWidgets.QLabel(Encryption)
        self.label.setGeometry(QtCore.QRect(310, 230, 251, 41))
        self.label.setStyleSheet("font:bold;\n"
"font-size: 20pt;\n"
"color: rgb(85, 0, 127)")
        self.label.setObjectName("label")
        self.time_label = QtWidgets.QLabel(Encryption)
        self.time_label.setGeometry(QtCore.QRect(570, 230, 301, 41))
        self.time_label.setStyleSheet("font:bold;\n"
"font-size: 15pt")
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.second_label = QtWidgets.QLabel(Encryption)
        self.second_label.setGeometry(QtCore.QRect(870, 230, 21, 41))
        self.second_label.setStyleSheet("font:bold;\n"
"font-size: 15pt")
        self.second_label.setObjectName("second_label")
        self.cbc_button = QtWidgets.QPushButton(Encryption)
        self.cbc_button.setGeometry(QtCore.QRect(210, 360, 121, 31))
        self.cbc_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.cbc_button.setObjectName("cbc_button")
        self.ecb_button = QtWidgets.QPushButton(Encryption)
        self.ecb_button.setGeometry(QtCore.QRect(350, 360, 121, 31))
        self.ecb_button.setStyleSheet("font: bold;\n"
"font-size: 13pt;\n"
"color: rgb(0, 0, 127)")
        self.ecb_button.setObjectName("ecb_button")
        self.team_label = QtWidgets.QLabel(Encryption)
        self.team_label.setGeometry(QtCore.QRect(920, 70, 381, 71))
        self.team_label.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: bold")
        self.team_label.setObjectName("team_label")

        self.retranslateUi(Encryption)
        QtCore.QMetaObject.connectSlotsByName(Encryption)

    def retranslateUi(self, Encryption):
        _translate = QtCore.QCoreApplication.translate
        Encryption.setWindowTitle(_translate("Encryption", "Dialog"))
        self.back_button.setText(_translate("Encryption", "Back"))
        self.browse_button.setText(_translate("Encryption", "Browse"))
        self.aes_button.setText(_translate("Encryption", "AES"))
        self.des_button.setText(_translate("Encryption", "DES"))
        self.rc4_button.setText(_translate("Encryption", "RC4"))
        self.choose_label.setText(_translate("Encryption", "Choose your picture"))
        self.key_label.setText(_translate("Encryption", "Enter your key"))
        self.key_edit.setPlaceholderText(_translate("Encryption", "Type here!"))
        self.img_label.setText(_translate("Encryption", "Your picture"))
        self.img_label_2.setText(_translate("Encryption", "Encrypt Picture"))
        self.label.setText(_translate("Encryption", "Running time:"))
        self.second_label.setText(_translate("Encryption", "s"))
        self.cbc_button.setText(_translate("Encryption", "CBC Mode"))
        self.ecb_button.setText(_translate("Encryption", "ECB Mode"))
        self.team_label.setText(_translate("Encryption", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Cryptography Theory </span></p><p align=\"center\"><span style=\" font-size:14pt;\">Made by Team07</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Encryption = QtWidgets.QDialog()
    ui = Ui_Encryption()
    ui.setupUi(Encryption)
    Encryption.show()
    sys.exit(app.exec_())
