# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\project_ltmm\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryptographyTheory(object):
    def setupUi(self, CryptographyTheory):
        CryptographyTheory.setObjectName("CryptographyTheory")
        CryptographyTheory.resize(1602, 978)
        self.team_label = QtWidgets.QLabel(CryptographyTheory)
        self.team_label.setGeometry(QtCore.QRect(350, 310, 881, 111))
        self.team_label.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: bold;\n"
"font-size: 30pt;")
        self.team_label.setObjectName("team_label")
        self.en_button = QtWidgets.QPushButton(CryptographyTheory)
        self.en_button.setGeometry(QtCore.QRect(680, 530, 231, 71))
        self.en_button.setStyleSheet("color: rgb(0, 0, 127);\n"
"font-size: 15pt;\n"
"font: bold")
        self.en_button.setObjectName("en_button")
        self.de_button = QtWidgets.QPushButton(CryptographyTheory)
        self.de_button.setGeometry(QtCore.QRect(680, 630, 231, 71))
        self.de_button.setStyleSheet("color: rgb(0, 0, 127);\n"
"font-size: 15pt;\n"
"font: bold")
        self.de_button.setObjectName("de_button")
        self.team_label_2 = QtWidgets.QLabel(CryptographyTheory)
        self.team_label_2.setGeometry(QtCore.QRect(470, 420, 671, 61))
        self.team_label_2.setStyleSheet("color: rgb(255, 0, 255);\n"
"font: bold;\n"
"font-size: 30pt")
        self.team_label_2.setObjectName("team_label_2")

        self.retranslateUi(CryptographyTheory)
        QtCore.QMetaObject.connectSlotsByName(CryptographyTheory)

    def retranslateUi(self, CryptographyTheory):
        _translate = QtCore.QCoreApplication.translate
        CryptographyTheory.setWindowTitle(_translate("CryptographyTheory", "Dialog"))
        self.team_label.setText(_translate("CryptographyTheory", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Cryptography Theory - Team07</span></p></body></html>"))
        self.en_button.setText(_translate("CryptographyTheory", "Encrypt"))
        self.de_button.setText(_translate("CryptographyTheory", "Decrypt"))
        self.team_label_2.setText(_translate("CryptographyTheory", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Class: 137307 - Teacher: Do Trong Tuan</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CryptographyTheory = QtWidgets.QDialog()
    ui = Ui_CryptographyTheory()
    ui.setupUi(CryptographyTheory)
    CryptographyTheory.show()
    sys.exit(app.exec_())
